### ISSUE TITLE
goto_*() arguments no longer work

### ISSUE THREAD

**Issue by filyp** [drybalka/tree-climber.nvim#4]
Having this line (as instructed in readme):
```
vim.keymap.set({'n', 'v', 'o'}, 'J', require('tree-climber').goto_next({ highlight = true }), keyopts)
```
raises:
```
Error detected while processing /home/filip/.config/nvim/init.vim:
line  160:
E5108: Error executing lua vim/keymap.lua:0: rhs: expected string|function, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/keymap.lua: in function 'set'
        [string ":lua"]:4: in main chunk
E325: ATTENTION
```

Seems to be related to https://github.com/neovim/neovim/issues/20532

**Comment by drybalka** [comment]
I think I know the reason for this error and it is a bit simpler. In the readme the line is: 
```
vim.keymap.set({'n', 'v', 'o'}, 'J', require('tree-climber').goto_next, keyopts)
```
, which passes a function `require('tree-climber').goto_next` into the `keymap.set`. 

In your case you pass the result of function call `require('tree-climber').goto_next()` (note the brackets after the `goto_next`) and this result is nil. The easiest solution is to wrap it in the anonymous function:
```
vim.keymap.set({ 'n', 'v', 'o' }, 'J', function()
  climber.goto_next({ highlight = true })
end, keyopts)
```

Hope this helps (and if yes please close the issue).
